version: '3.3'
services:
  eureka:
    image: sanjaypatni5/eureka 
    restart: on-failure
    networks:
      - custom3
    container_name: eureka 
    ports:
      - "8761:8761"
  mysqldb:
    image: mysql:8.3 
    restart: always
    environment:
       MYSQL_DATABASE: playclips
       MYSQL_ROOT_PASSWORD: demo
       MYSQL_ROOT_HOST: '%'
       MYSQL_SERVER: mysqldb
    networks:
      - custom3
    volumes:
       - mysql-volume:/var/lib/mysql
  api:
    image: sanjaypatni5/api
    restart: on-failure
    networks:
      - custom3
    external_links:
      - eureka
    container_name: api
    ports:
      - "5003:5003"
    depends_on:
       - mysqldb
    volumes:
      - ~/config:/var/config/
    environment:
       MYSQL_SERVER: mysqldb
       EUREKA_SERVER: http://eureka:8761/
       API_SERVER: api-jwt
       dbHost: dist_mysqldb_1
       bcUrl: HTTP://127.0.0.1:7545
#      bcUrl: https://eth-mainnet.g.alchemy.com/v2/2SoGMSPGxpLZv3ezQKEEyT1I_8-J6VrL
       waToken: EAALo0iuubooBO4eZA15qqavCyymJOiWX08ZALOMor1zfm1CZC0Cwc53aYaJSnyNOtPgBkaEGqr5nRIz55KhuOOCsBKdKKZAt9JQ79gMpRQ1bnLjz6YolUoUpm8Rq2wzZABgbYF1PyLR6EoAwiy36yq0RZAN61NOUzAXmSbCZAx5lZCxisQ8GizcUZBpaFD5JN9nZAOjInuyACXdNT0IzBESeE2vwgdO5yQGNDY4pgZD

  content:
    image: sanjaypatni5/content
    restart: on-failure
    networks:
      - custom3
    external_links:
      - eureka
    container_name: content
    ports:
      - "5008:5008"
    depends_on:
       - mysqldb
    volumes:
      - ~/config:/var/config
    environment:
       MYSQL_SERVER: mysqldb
       EUREKA_SERVER: http://eureka:8761
       dbHost: dist_mysqldb_1 
  upload:
    image: sanjaypatni5/upload
    restart: on-failure
    networks:
      - custom3
    external_links:
      - eureka
    container_name: upload
    ports:
      - "5009:5009"
    depends_on:
       - mysqldb
    volumes:
      - ~/config:/var/config
    environment:
       MYSQL_SERVER: mysqldb
       EUREKA_SERVER: http://eureka:8761

  web3j:
    image: sanjaypatni5/web3j
    restart: on-failure
    networks:
      - custom3
    external_links:
      - eureka
    container_name: web3j
    ports:
      - "8096:8096"
    depends_on:
       - mysqldb
    volumes:
      - ~/config:/var/config/
    environment:
       MYSQL_SERVER: mysqldb
       EUREKA_SERVER: http://eureka:8761/
       dbHost: latest-server-mysqldb-1
#      bcUrl: https://eth-mainnet.g.alchemy.com/v2/2SoGMSPGxpLZv3ezQKEEyT1I_8-J6VrL
  apigateway:
    image: sanjaypatni5/apigateway 
    restart: on-failure
    networks:
      - custom3
    container_name: apigateway 
    ports:
      - "8095:8095"
    environment:
       APP_SERVER: api
       EUREKA_SERVER: http://eureka:8761/
volumes:
  mysql-volume:
networks:
  custom3:
