export class Clip {
    id: string;
    title: string;
    description: string;
    type: string = "";
    application: string;
    login: string;
    link: string;
    rating: number = 0;
    srating: String;
    thumbnail: string;
    showAudio : boolean;
    showRecord : boolean;
    showVideo : boolean;
    showImage : boolean;
    showYTube : boolean;
    showText : boolean;
    showPdf : boolean;
    showContact : boolean;
    showTodo : boolean;
    showChat : boolean;
    showAppt : boolean;
    showLink : boolean;
    showItem : boolean;
    srating1 : boolean;
    srating2 : boolean;
    srating3 : boolean;
    srating4 : boolean;
    srating5 : boolean;
    startDate: string;
    endDate: string;
    taskStatus : string;
    email : string;
    phone: string;
    fileName: string;
    disabled : boolean = false;
    ilink : string;
    archine : number = 0;
    price : number = 0.0;
    preview : boolean = false;
    jwt : string;
    base64Bytes : any = "";
    fileType : string = "";
    base64String : any = "data:" + this.type + "/" + this.fileType + ";base64," + this.base64Bytes;
    active : string = "panel";
    playType : string = "playclip";
  }
