export class Api {
  protocol = "https";
  server = "core4ed.com";
  kafka = "core4ed.com:5014";
  blockchainTransaction = this.protocol + "://" + this.server + "/api/transaction";
  publish = this.protocol + "://" + this.kafka + "/event/publish";
  visit = this.protocol + "://" + this.server + "/api/visit";
  text = "http" + "://" + this.server +":5011" +  "/text";
  email = "http" + "://" + this.server +":5011" +  "/email";
  upload = this.protocol + "://" + this.server + "/upload/s3/upload";
  uploadv = this.protocol + "://" + this.server + "/upload/s3/video/upload";
  uploadCrypt = this.protocol + "://" + this.server + "/upload/s3/uploadCrypt";
  uploadBytes = this.protocol + "://" + this.server + "/upload/s3/uploadBytes";
  download = this.protocol + "://" + this.server + "/upload/s3/download";
  audio = "http://" + this.server + "/content/audio.html?login=";
  auth = this.protocol + "://" + this.server + "/api/authenticate";
  at = this.protocol + "://" + this.server + "/api/accesstoken?client_id=demo&client_secret=demo&login=";
  userCreate = this.protocol  + "://" + this.server + "/api/register";
  userDetailsCreate = this.protocol  + "://" + this.server + "/api/userdetails";
  userDelete = this.protocol  + "://" + this.server + "/api/user";
  user = this.protocol  + "://" + this.server + "/api/user";
  userDetailsDelete = this.protocol  + "://" + this.server + "/api/userdetails/";
  userGet = this.protocol  + "://" + this.server + "/api/user/get";
  clip =  this.protocol + "://" + this.server + "/api/clip" ;
  clipType =  this.protocol + "://" + this.server + "/api/clip/type" ;
  content =  this.protocol + "://" + this.server + "/content/content/";
  contentType =  this.protocol + "://" + this.server + "/content/content/type";
  contentcount =  this.protocol + "://" + this.server + "/content/contentcount/";
  like =  this.protocol + "://" + this.server + "/content/like/";
  object =  this.protocol + "://" + this.server + "/content/object/";
  archive =  this.protocol + "://" + this.server + "/content/archive/";
  archiveplayclip =  this.protocol + "://" + this.server + "/api/archiveplayclip";
  boughtplayclip =  this.protocol + "://" + this.server + "/api/boughtplayclip";
  archiveclip =  this.protocol + "://" + this.server + "/api/archiveclip";
  purge =  this.protocol + "://" + this.server + "/content/purge";
  purgeclip =  this.protocol + "://" + this.server + "/api/purgeclip";
  purgeplayclip =  this.protocol + "://" + this.server + "/api/purgeplayclip";
  unlike =  this.protocol + "://" + this.server + "/content/unlike/";
  subscription = this.protocol + "://" + this.server + "/content/subscription";
  subscription_uuid = this.protocol + "://" + this.server + "/content/subscription/uuid";
  playclips = this.protocol + "://" + this.server + "/api/playclip";
  youtube = "https://www.googleapis.com/youtube/v3/search?short&part=snippet&maxResults=50&type=video&videoDuration=short&key=AIzaSyDjsc4_LlCVoFVGUTar5T4o0zdS4zrS6Uk&q=";
  chat = "http://playclips-uat.com/message"
  st = this.protocol + "://" + this.server + "/api/stripetoken";
  wa = this.protocol + "://" + this.server + "/api/whatsapp?id=";
  charge = this.protocol + "://" + this.server + "/api/charge";
  mail = this.protocol + "://" + this.server + "/api/email?email=sanjaypatni@yahoo.com";
  sms = "http://localhost:8080/sms";
  objectCnt = this.protocol + "://" + this.server + "/content/objectCnt";
  objectCntLogin = this.protocol + "://" + this.server + "/content/objectCnt/login?login=";
}
